title: Grafana In Corporate Production Environment
description: >-
  Corporate production experience with Grafana by Dmitri K Klein.
email: dmitri.klein@y7mail.com
url: "https://your-username.github.io" # Replace with your GitHub Pages URL
baseurl: "" # Use "" if it's a user/organization site

# Theme and appearance
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "aqua" # Options: default, dark, mint, sunrise, etc.
locale: "en"
lang: "en"

# Author info
author:
  name: Dmitri K Klein
  avatar: "/assets/images/DK2025.JPG"
  bio: "Cloud-native observability professional"
  location: "Colorado, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/dmitriklein"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/your-handle"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Permalinks
permalink: /:year/:month/:day/:title/

# Markdown processor
markdown: kramdown
highlighter: rouge

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
